### ISSUE TITLE
Create tables and charts to show placement statistics

### ISSUE THREAD

**Issue by vascodes** [vascodes/rcss-placement-cell#5]
### TO DO:
- [x] Create table showcasing company names and no. of offers. 
- [x] Display total no. of offers in table.
- [x] Create table to show CTC Range and no. of students.
- [x] Create bar chart to show percentage of placements corresponding to year of placement.

### Some placement cell statistics is provided in below image:
![Image](https://user-images.githubusercontent.com/70539432/219935244-5e94a32f-1a30-488a-b889-23dbe518de01.png)

**Comment by Nithu-Roban** [comment]
completed
